import { Character } from "./character";

export const CHARACTERS: Character[]= [
  { id: 1, name: "Jon Snow", description: "Is really Aegon Targaryen! He Knows Nothing!!!"},
  { id: 2, name: "Sansa Stark", description: "Queen of the North!"},
  { id: 3, name: "Arya Stark", description: "Great Assassin! Night King Killer!"},
  { id: 4, name: "Bran Stark", description: "King of the Six Kingdoms. Also the Three-Eyed-Raven"},
  { id: 5, name: "Daenerys Targaryen", description: "Daenerys Stormborn of House Targaryen, the First of Her Name, Queen of the Andals and the First Men, Protector of the Seven Kingdoms, the Mother of Dragons, the Khaleesi of the Great Grass Sea, the Unburnt, the Breaker of Chains"},
  { id: 6, name: "Tyrion Lannister", description: "Hand of the King! He drinks and he knows things!"},
  { id: 7, name: "Cersei Lannister", description: "Former Queen. Will do anything for power and family"},
  { id: 8, name: "Jaime Lannister", description: "Kingslayer! Lover/brother to Cersei and loyal to her to a fault.  True father of all Cersei's kids"},
  { id: 9, name: "Tywin Lannister", description: "Father of Jaime, Cersei, and Tyrion. Driving force behind all three of them, for better or worse."},
  { id: 10, name: "Eddard Stark", description: "Aka 'Ned.' Father to the Stark Family and the cause of the story behind Game of Thrones."},
  { id: 11, name: "Catelyn Stark", description: "Mother of the Stark Family. Will do anything to protect her family."},
  { id: 12, name: "Robb Stark", description: "Former King of the North. Son of Ned and Catelyn. Murdered at his 'Red Wedding.'"},
  { id: 13, name: "Rickon Stark", description: "Son of Ned and Catelyn. Killed at the 'Battle of the Bastards.'"},
  { id: 14, name: "Robert Baratheon", description: "Former King of the Seven Kingdoms. Married to Cersei. Took over the throne from the 'Mad King.'"},
  { id: 15, name: "Stannis Baratheon", description: "Claimed the throne after Robert died. Sacrificed his family as a believer in the God of Light"},
  { id: 16, name: "Renly Baratheon", description: "Not as strong a leader as his family. Also tried to claim the throne."},
  { id: 17, name: "Joffrey Baratheon", description: "Former King. Lacked any moral compass. Son of Cersei"},
  { id: 18, name: "Tommen Baratheon", description: "Former King following his brother, Joffrey. Easily controlled by others, especially the High Sparrow. Son of Cersei."},
  { id: 19, name: "Myrcella Baratheon", description: "Lived in Dorne to connect House Baratheon and House Martell. Daughter of Cersei."},
  { id: 20, name: "Ser Brienne Tarth", description: "Master of the Kingsguard. First Lady Knight"},
  { id: 21, name: "Ser Davos Seaworth", description: "Master of Ships. Loyal to Jon Snow and a very moral leader."},
  { id: 22, name: "Podrick Payne", description: "Part of Kingsguard, was squire to Brienne. A woman's gift in disguise ;)"},
  { id: 23, name: "Bronn", description: "Master of Coin. Very opportunistic and driven by money. Loyal to the highest bidder."},
  { id: 24, name: "Grey Worm", description: "Commander of the Unsullied. Loyal to Daenerys."},
  { id: 25, name: "Missandei", description: "Loyal Advisor to Daenerys. Freely served her."},
  { id: 26, name: "Lord Varys", description: "Former Master of Whispers. Loyal to the people of the Seven Kingdoms."},
  { id: 27, name: "Ser Jorah Mormont", description: "Exiled Knight who was loyal & in love with Daenerys."},
  { id: 28, name: "Lyanna Mormont", description: "Youngest leader of House Mormont. Loyal to the North at all costs. Great leader despite her age."},
  { id: 29, name: "Joer Mormont", description: "Former Leader of the Night's Watch. Betrayed by some of his men."},
  { id: 30, name: "Tormund Giantsbase", description: "A Free Folk. Eventaully loyal to Jon Snow. Great fighter and protector."},
  { id: 31, name: "Ygritte", description: "Original lover of Jon Snow. A Free Folk who was torn between her people and her love for Jon"},
  { id: 32, name: "Osha", description: "A Free Folk who helped protect Bran doing his journey to become Three-Eyed-Raven"},
  { id: 33, name: "Samwell Tarly", description: "Grand Maester of Six Kingdoms. Loyal to Jon and very moral character."},
  { id: 34, name: "Gilly", description: "Lover of Samwell. She found the true indentity of Jon Snow by accident. A Free Folk who escaped Craster."},
  { id: 35, name: "Craster", description: "An enslaver North of the Wall who 'gave' all male born babies as gifts to the Night King."},
  { id: 36, name: "Night King", description: "Leader of the White Walkers and Undead Army. Wants to kill the Three-Eyed-Raven and erase all memory of humans."},
  { id: 37, name: "Theon Greyjoy", description: "Grew up with the Stark Family as a squire. Later torn by his loyalty to the Starks and his ties to his blood family."},
  { id: 38, name: "Yara Greyjoy", description: "Leader of the Iron Islands. Great leader who fights for the right reasons."},
  { id: 39, name: "Euron Greyjoy", description: "Formerly took over leadership of the Iron Islands before Yara regained it. Crazy in his own right and thinks he is eventual King next to Cersei."},
  { id: 40, name: "Sandor Clegane", description: "Aka 'The Hound.' More logical than moral but eventually protects those he deems worthy."},
  { id: 41, name: "Gregor Clegane", description: "Aka 'The Mountain.' Brother to Sandor. Purely evil and is Kingsguard to Cersei."},
  { id: 42, name: "Petyr Baelish", description: "Aka 'Littlefinger.' Former Master of Coin. Does anything he can to progress his power and is reason for all the evil plans until his death."},
  { id: 43, name: "Khal Drogo", description: "Enslaved and married Daenerys while she was exiled to Essos. Former leader of the Dothraki."},
  { id: 44, name: "Melisandre", description: "Aka 'The Red Woman.' Sorceress and follower of the God of Light. Driven by her visions which leads her to not necessarily be moral. Eventually picks the right side."},
  { id: 45, name: "Olenna Tyrell", description: "Grandmother to Margaery and Loras. Will do anything for her family."},
  { id: 46, name: "Margaery Tyrell", description: "Former Queen next to Tommen. Did what she could in the circumstance she was in. Was beloved by the people."},
  { id: 47, name: "Loras Tyrell", description: "Great fighter but flawed by his love that went against what was expected of him."},
  { id: 48, name: "Oberyn Martell", description: "Aka 'The Red Viper.' Great fighter and leader but driven by revenge for his sister's death."},
  { id: 49, name: "Ellaria Sand", description: "Lover to Oberyn. Leader of the 'Sand Snakes.'"},
  { id: 50, name: "Tyene Sand", description: "Daughter of Ellaria. Member of the 'Sand Snakes.' Skilled with the use of two long daggers."},
  { id: 51, name: "Obarra Sand", description: "Member of the 'Sand Snakes.' Skilled with a spear."},
  { id: 52, name: "Nymeria Sand", description: "Member of the 'Sand Snakes.' Skilled with a whip."},
  { id: 53, name: "Gendry Baratheon", description: "Lord of House Baratheon. Loyal to Jon Snow and in love with Arya. Very moral character."},
  { id: 54, name: "Hodor", description: "Short of 'Hold the door!' His last words saving Bran from the undead."},
  { id: 55, name: "Walder Frey", description: "Betrayed the Starks. Host to the 'Red Wedding.'"},
  { id: 56, name: "Ramsay Bolton", description: "Driven by evil. Tortured Theon and all those under his control. The other half of the 'Battle of the Bastards.'"},
  { id: 57, name: "Roose Bolton", description: "Betrayed the Starks with Walder. Also part of the 'Red Wedding.'"},
  { id: 58, name: "Daario Naharis", description: "Former lover of Daenerys. Leader of the Bay of Dragons as Daenerys leaves to take Westeros."},
  { id: 59, name: "High Sparrow", description: "Blindly driven by faith, but turned out to be evil."},
  { id: 60, name: "Beric Dondarrion", description: "Leader of the 'Brotherhood Without Banners.' Believer in the God of Light. Was killed and brought back to life multiple times."},
  { id: 61, name: "Lisa Arryn", description: "Catelyn Stark's sister. Betrayed her family for the love of Petyr."},
  { id: 62, name: "Robert Arryn", description: "Aka 'Robin.' Coddled by Lisa. Does not know control or morality.  Spoiled brat basically."},
  { id: 63, name: "Qyburn", description: "Former Maester and practicer of the Dark Arts. Was Hand of the Queen to Cersei."},
  { id: 64, name: "Jaqen H'ghar", description: "Member of the Faceless Men. Teaches Arya to be a 'Faceless' assassin"},
  { id: 65, name: "Thoros of Myr", description: "Member of the 'Brotherhood Without Banners.' Believer in the God of Light. Close friend to Beric."},
  { id: 66, name: "Meera Reed", description: "Saved Bran from the undead and carried Bran from his journey to being Three-Eyed-Raven"},
  { id: 67, name: "Jojen Reed", description: "Brother of Meera. Taught Bran how to control his warging abilities."},
  { id: 68, name: "Eddison Tollet", description: "Leader of the Night's Watch following Jon. Loyal to Jon Snow."},
  { id: 69, name: "Barristan Selmy", description: "Loyal to Daenerys though that was not the start. Former knight of Robert."}
]
